name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install test dependencies
        run: |
          pip install pytest
          
      - name: Run routing logic tests
        run: |
          python tests/test_simple.py
          
      - name: Run pytest
        run: |
          pytest tests/ -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build -t ds-assistant:${{ github.sha }} .
          
      - name: Verify image creation
        run: |
          docker images | grep ds-assistant